local _, MountSpy = ...

MountSpy_Achievements = {
    {id = 614, name = "For the Alliance!"},
    {id = 619, name = "For the Horde!"},
    {id = 2136, name = "Glory of the Hero"},
    {id = 2138, name = "Glory of the Raider (25 Player)"},
    {id = 2143, name = "Leading the Cavalry"},
    {id = 2144, name = "What A Long, Strange Trip It's Been"},
    {id = 2536, name = "Mountain o' Mounts"},
    {id = 2537, name = "Mountain o' Mounts"},
    {id = 4079, name = "A Tribute to Immortality"},
    {id = 4156, name = "A Tribute to Immortality"},
    {id = 4602, name = "Glory of the Icecrown Raider (10 player)"},
    {id = 4603, name = "Glory of the Icecrown Raider (25 player)"},
    {id = 4845, name = "Glory of the Cataclysm Hero"},
    {id = 4853, name = "Glory of the Cataclysm Raider"},
    {id = 5828, name = "Glory of the Firelands Raider"},
    {id = 5866, name = "The Molten Front Offensive"},
    {id = 6169, name = "Glory of the Dragon Soul Raider"},
    {id = 6375, name = "Challenge Conqueror: Silver"},
    {id = 6682, name = "Guild Glory of the Pandaria Raider"},
    {id = 6827, name = "Pandaren Ambassador"},
    {id = 6828, name = "Pandaren Ambassador"},
    {id = 6927, name = "Glory of the Pandaria Hero"},
    {id = 6932, name = "Glory of the Pandaria Raider"},
    {id = 7860, name = "We're Going to Need More Saddles"},
    {id = 8124, name = "Glory of the Thundering Raider"},
    {id = 8302, name = "Mount Parade"},
    {id = 8304, name = "Mount Parade"},
    {id = 8398, name = "Ahead of the Curve: Garrosh Hellscream (10 Player)"},
    {id = 8454, name = "Glory of the Orgrimmar Raider"},
    {id = 8898, name = "Challenge Warlord: Silver"},
    {id = 8985, name = "Glory of the Draenor Raider"},
    {id = 9396, name = "Glory of the Draenor Hero"},
    {id = 9496, name = "Warlord's Deathwheel"},
    {id = 9598, name = "Mountacular"},
    {id = 9669, name = "Guild Glory of the Draenor Raider"},
    {id = 9705, name = "Advanced Husbandry"},
    {id = 9706, name = "The Stable Master"},
    {id = 9713, name = "Awake the Drakes"},
    {id = 9909, name = "Heirloom Hoarder"},
    {id = 9909, name = "Heirloom Hoarder"},
    {id = 10018, name = "Draenor Pathfinder"},
    {id = 10149, name = "Glory of the Hellfire Raider"},
    {id = 10356, name = "Lord of the Reins"},
    {id = 11066, name = "Underbelly Tycoon"},
    {id = 11163, name = "Glory of the Legion Hero"},
    {id = 11176, name = "Remember to Share"},
    {id = 11180, name = "Glory of the Legion Raider"},
    {id = 11987, name = "Glory of the Argus Raider"},
    {id = 12103, name = "...And Chew Mana Buns"},
    {id = 12401, name = "Glory of the Ulduar Raider"},
    {id = 12806, name = "Glory of the Uldir Raider"},
    {id = 12812, name = "Glory of the Wartorn Hero"},
    {id = 12866, name = "100 Exalted Reputations"},
    {id = 12931, name = "No Stable Big Enough"},
    {id = 12933, name = "A Horde of Hoofbeats"},
    {id = 13250, name = "Battle for Azeroth Pathfinder, Part Two"},
    {id = 13315, name = "Glory of the Dazar'alor Raider"},
    {id = 13517, name = "Two Sides to Every Tale"},
    {id = 13541, name = "Mecha-Done"},
    {id = 13638, name = "Undersea Usurper"},
    {id = 13687, name = "Glory of the Eternal Raider"},
    {id = 13994, name = "Through the Depths of Visions"},
    {id = 14145, name = "Battle for Azeroth Keystone Master: Season Four"},
    {id = 14146, name = "Glory of the Ny'alotha Raider"},
    {id = 14322, name = "Glory of the Shadowlands Hero"},
    {id = 14353, name = "Ardenweald's a Stage"},
    {id = 14355, name = "Glory of the Nathria Raider"},
    {id = 14532, name = "Shadowlands Keystone Master: Season One"},
    {id = 14570, name = "Twisting Corridors: Layer 8"},
    {id = 15035, name = "On the Offensive"},
    {id = 15064, name = "Breaking the Chains"},
    {id = 15078, name = "Shadowlands Keystone Master: Season Two"},
    {id = 15089, name = "Flawless Master (Layer 12)"},
    {id = 15130, name = "Glory of the Dominant Raider"},
    {id = 15178, name = "Fake It 'Til You Make It"},
    {id = 15254, name = "The Jailer's Gauntlet: Layer 4"},
    {id = 15310, name = "A Tour of Towers"},
    {id = 15322, name = "Flawless Master (Layer 16)"},
    {id = 15336, name = "From A to Zereth"},
    {id = 15491, name = "Glory of the Sepulcher Raider"},
    {id = 15499, name = "Shadowlands Keystone Master: Season Three"},
    {id = 15684, name = "Fates of the Shadowlands Raids"},
    {id = 15690, name = "Shadowlands Keystone Master: Season Four"},
    {id = 15834, name = "Thanks for the Carry!"},
    {id = 16295, name = "Glory of the Dragonflight Hero"},
    {id = 16355, name = "Glory of the Vault Raider"},
    {id = 16649, name = "Dragonflight Keystone Master: Season One"},
    {id = 17844, name = "Dragonflight Keystone Master: Season Two"},
    {id = 18251, name = "Glory of the Aberrus Raider"},
    {id = 18646, name = "Whodunnit?"}
}

MountSpy.HelpData = {
    {command = "show", description = "Shows the main MountSpy window."},
    {command = "hide", description = "Hides the main MountSpy window."},
    {command = "getinfo", description = "Gets info about the targeted player's mount."},
    {command = "history", description = "Shows the last 10 mounts that MountSpy has identified."},
    {command = "clearhistory", description = "Clears the MountSpy mount history."},
    {command = "match", description = "Attempts to put you on a mount that matches the target's mount."},
    {command = "version", description = "Displays the MountSpy version that you are currently using."},
    {command = "quiet", description = "Disables MountSpy startup messages."},
    {command = "self", description = "Toggles whether to show your mount info when you select yourself."},
    {command = "instance", description = "Toggles whether to show mount info when in an instance."},
    {command = "bg", description = "Toggles whether to show mount info when in a battleground."},
    {command = "arena", description = "Toggles whether to show mount info when in an arena."},
    {command = "combat", description = "Toggles whether to show mount info when in combat."},
    {command = "shapeshift", description = "Toggles whether to show player travel forms, etc."},
    {
        command = "auto",
        description = "Toggles whether to show mount info automatically when you click on a player character."
    }
}
