local _, MountSpy = ...

MountSpy_Achievements = {
    {id = 9496, name = "Warlord's Deathwheel"},
    {id = 15254, name = "The Jailer's Gauntlet: Layer 4"},
    {id = 13994, name = "Through the Depths of Visions"},
    {id = 14570, name = "Twisting Corridors: Layer 8"},
    {id = 15310, name = "A Tour of Towers"},
    {id = 15178, name = "Fake It 'Til You Make It"},
    {id = 15089, name = "Flawless Master (Layer 12)"},
    {id = 15322, name = "Flawless Master (Layer 16)"},
    {id = 40438, name = "Glory of the War Within Delver"},
    {id = 41966, name = "Mastering the Visions"},
    {id = 42212, name = "Titan Console Overcharged"},
    {id = 61906, name = "Glory of the Midnight Delver"},
    {id = 61799, name = "Let Me Solo Him: Nullaeus"},
    {id = 614, name = "For the Alliance!"},
    {id = 619, name = "For the Horde!"},
    {id = 9706, name = "The Stable Master"},
    {id = 9540, name = "The Stable Master"},
    {id = 9705, name = "Advanced Husbandry"},
    {id = 9539, name = "Advanced Husbandry"},
    {id = 12103, name = "...And Chew Mana Buns"},
    {id = 14353, name = "Ardenweald's a Stage"},
    {id = 15035, name = "On the Offensive"},
    {id = 16492, name = "Into the Storm"},
    {id = 40702, name = "Khaz Algar Glyph Hunter"},
    {id = 40539, name = "The Derby Dash"},
    {id = 61017, name = "Phase-Lost-and-Found"},
    {id = 41980, name = "Vigilante"},
    {id = 62385, name = "Staring Into The Void"},
    {id = 61584, name = "Midnight Glyph Hunter"},
    {id = 61263, name = "Treasures of Harandar"},
    {id = 2143, name = "Leading the Cavalry"},
    {id = 2536, name = "Mountain o' Mounts"},
    {id = 2537, name = "Mountain o' Mounts"},
    {id = 7860, name = "We're Going to Need More Saddles"},
    {id = 7862, name = "We're Going to Need More Saddles"},
    {id = 8304, name = "Mount Parade"},
    {id = 8302, name = "Mount Parade"},
    {id = 9598, name = "Mountacular"},
    {id = 9599, name = "Mountacular"},
    {id = 10356, name = "Lord of the Reins"},
    {id = 10355, name = "Lord of the Reins"},
    {id = 12931, name = "No Stable Big Enough"},
    {id = 12932, name = "No Stable Big Enough"},
    {id = 12933, name = "A Horde of Hoofbeats"},
    {id = 12934, name = "A Horde of Hoofbeats"},
    {id = 15834, name = "Thanks for the Carry!"},
    {id = 15833, name = "Thanks for the Carry!"},
    {id = 62103, name = "Insurmountable Collection"},
    {id = 62096, name = "Insurmountable Collection"},
    {id = 9713, name = "Awake the Drakes"},
    {id = 11176, name = "Remember to Share"},
    {id = 9909, name = "Heirloom Hoarder"},
    {id = 6828, name = "Pandaren Ambassador"},
    {id = 6827, name = "Pandaren Ambassador"},
    {id = 12866, name = "100 Exalted Reputations"},
    {id = 62190, name = "Life of the Party"},
    {id = 2144, name = "What A Long, Strange Trip It's Been"},
    {id = 18646, name = "Whodunnit?"},
    {id = 2136, name = "Glory of the Hero"},
    {id = 4845, name = "Glory of the Cataclysm Hero"},
    {id = 6927, name = "Glory of the Pandaria Hero"},
    {id = 9396, name = "Glory of the Draenor Hero"},
    {id = 11163, name = "Glory of the Legion Hero"},
    {id = 12812, name = "Glory of the Wartorn Hero"},
    {id = 14322, name = "Glory of the Shadowlands Hero"},
    {id = 16295, name = "Glory of the Dragonflight Hero"},
    {id = 14145, name = "Battle for Azeroth Keystone Master: Season Four"},
    {id = 6375, name = "Challenge Conqueror: Silver"},
    {id = 8898, name = "Challenge Warlord: Silver"},
    {id = 14532, name = "Shadowlands Keystone Master: Season One"},
    {id = 15078, name = "Shadowlands Keystone Master: Season Two"},
    {id = 15499, name = "Shadowlands Keystone Master: Season Three"},
    {id = 15690, name = "Shadowlands Keystone Master: Season Four"},
    {id = 16649, name = "Dragonflight Keystone Master: Season One"},
    {id = 17844, name = "Dragonflight Keystone Master: Season Two"},
    {id = 19011, name = "Dragonflight Keystone Master: Season Three"},
    {id = 19782, name = "Dragonflight Keystone Master: Season Four"},
    {id = 20525, name = "The War Within Keystone Master: Season One"},
    {id = 41533, name = "The War Within Keystone Master: Season Two"},
    {id = 40951, name = "The War Within Keystone Legend: Season Two"},
    {id = 41973, name = "The War Within Keystone Master: Season Three"},
    {id = 42172, name = "The War Within Keystone Legend: Season Three"},
    {id = 61256, name = "Midnight Keystone Master: Season One"},
    {id = 61258, name = "Midnight Keystone Legend: Season One"},
    {id = 2138, name = "Glory of the Raider (25 Player)"},
    {id = 12401, name = "Glory of the Ulduar Raider"},
    {id = 4602, name = "Glory of the Icecrown Raider (10 player)"},
    {id = 4603, name = "Glory of the Icecrown Raider (25 player)"},
    {id = 4853, name = "Glory of the Cataclysm Raider"},
    {id = 5828, name = "Glory of the Firelands Raider"},
    {id = 6169, name = "Glory of the Dragon Soul Raider"},
    {id = 6932, name = "Glory of the Pandaria Raider"},
    {id = 6682, name = "Guild Glory of the Pandaria Raider"},
    {id = 8124, name = "Glory of the Thundering Raider"},
    {id = 8454, name = "Glory of the Orgrimmar Raider"},
    {id = 8985, name = "Glory of the Draenor Raider"},
    {id = 9669, name = "Guild Glory of the Draenor Raider"},
    {id = 10149, name = "Glory of the Hellfire Raider"},
    {id = 11180, name = "Glory of the Legion Raider"},
    {id = 11987, name = "Glory of the Argus Raider"},
    {id = 12806, name = "Glory of the Uldir Raider"},
    {id = 13315, name = "Glory of the Dazar'alor Raider"},
    {id = 13687, name = "Glory of the Eternal Raider"},
    {id = 14146, name = "Glory of the Ny'alotha Raider"},
    {id = 14355, name = "Glory of the Nathria Raider"},
    {id = 15130, name = "Glory of the Dominant Raider"},
    {id = 15491, name = "Glory of the Sepulcher Raider"},
    {id = 16355, name = "Glory of the Vault Raider"},
    {id = 18251, name = "Glory of the Aberrus Raider"},
    {id = 19349, name = "Glory of the Dream Raider"},
    {id = 40232, name = "Glory of the Nerub-ar Raider"},
    {id = 41286, name = "Glory of the Liberation of Undermine Raider"},
    {id = 41597, name = "Glory of the Omega Raider"},
    {id = 61380, name = "Glory of the Midnight Raider"},
    {id = 8398, name = "Ahead of the Curve: Garrosh Hellscream"},
    {id = 8399, name = "Ahead of the Curve: Garrosh Hellscream"},
    {id = 4079, name = "A Tribute to Immortality"},
    {id = 4156, name = "A Tribute to Immortality"},
    {id = 19574, name = "Awakening the Dragonflight Raids"},
    {id = 11066, name = "Underbelly Tycoon"},
    {id = 5866, name = "The Molten Front Offensive"},
    {id = 10018, name = "Draenor Pathfinder"},
    {id = 13517, name = "Two Sides to Every Tale"},
    {id = 13638, name = "Undersea Usurper"},
    {id = 13541, name = "Mecha-Done"},
    {id = 13250, name = "Battle for Azeroth Pathfinder, Part Two"},
    {id = 15064, name = "Breaking the Chains"},
    {id = 15336, name = "From A to Zereth"},
    {id = 19458, name = "A World Awoken"},
    {id = 19479, name = "Wake Me Up"},
    {id = 19482, name = "Army of the Fed"},
    {id = 19486, name = "Across the Isles"},
    {id = 19485, name = "Closing Time"},
    {id = 19483, name = "Flight Club"},
    {id = 20501, name = "Back from the Beyond"},
    {id = 17785, name = "Que Zara(lek), Zara(lek)"},
    {id = 19481, name = "Centaur of Attention"},
    {id = 40956, name = "I'm On Island Time"},
    {id = 40953, name = "A Farewell to Arms"},
    {id = 41201, name = "You Xal Not Pass"},
    {id = 41133, name = "Isle Remember You"},
    {id = 61451, name = "Worldsoul-Searching"},
    {id = 62386, name = "Light Up the Night"},
}

MountSpy.HelpData = {
    {command = "show", description = "Shows the main MountSpy window."},
    {command = "hide", description = "Hides the main MountSpy window."},
    {command = "getinfo", description = "Gets info about the targeted player's mount."},
    {command = "history", description = "Shows the last 10 mounts that MountSpy has identified."},
    {command = "clearhistory", description = "Clears the MountSpy mount history."},
    {command = "match", description = "Attempts to put you on a mount that matches the target's mount."},
    {command = "version", description = "Displays the MountSpy version that you are currently using."},
    {command = "quiet", description = "Disables MountSpy startup messages."},
    {command = "self", description = "Toggles whether to show your mount info when you select yourself."},
    {command = "instance", description = "Toggles whether to show mount info when in an instance."},
    {command = "bg", description = "Toggles whether to show mount info when in a battleground."},
    {command = "arena", description = "Toggles whether to show mount info when in an arena."},
    {command = "combat", description = "Toggles whether to show mount info when in combat."},
    {command = "shapeshift", description = "Toggles whether to show player travel forms, etc."},
    {
        command = "auto",
        description = "Toggles whether to show mount info automatically when you click on a player character."
    }
}
